---
framework: jest
tier: large
postMerge: 
  pattern: 
    - "./tests/format/js/**/*.spec.js"
    - "./tests/integration/__tests__/*.js"
preMerge:
  pattern:
    - "./tests/format/js/**/*.spec.js"
    - "./tests/integration/__tests__/*.js"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 2.1
