---
framework: jest
postMerge: 
  pattern: 
    - "./tests/integration/__tests__/*.js"
preMerge:
  pattern:
    - "./tests/integration/__tests__/*.js"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 1.0
