---
framework: "jest"
postMerge:
    pattern:
    - "./tests/format/js/**/*.spec.js"
    - "./tests/integration/__tests__/*.js"
preMerge:
    pattern:
    - "./tests/format/js/**/*.spec.js"
    - "./tests/integration/__tests__/*.js"
preRun:
    - yarn install
    - yarn run build
postRun:
    - yarn --version
version: 2.0
